Repository powerdns-operator/PowerDNS-Operator, pull requests merged in 2025-08, with the labels that each got.

#188 bump golang 1.25 and dependencies
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: dependencies, github_actions, go

#187 feat: Add support passing a custom CA
  DEV_SETUP.md
  README.md
  cmd/main.go
  docs/introduction/getting-started.md
Labels: enhancement

#189 docs(readme): add demo video
  README.md
Labels: documentation
